python train.py \
    --device 0,1 \
    --batch-size 16 \
    --img 608 608 \
    --data cfg/data.yaml \
    --cfg cfg/satellite-anchor-level18.cfg \
    --hyp cfg/hyp.yaml \
    --weights weights/yolov4.conv.137 \
    --name level18 \
    --single-cls \
    --epochs 400